---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Hersenkraker
description: Leer hoe je een quiz maakt
version: 4.0.2
last_tested: 2018-10-03
steps:
- title: Inleiding
  completion: engaged
- title: Vragen maken
- title: Een tijdklok toevoegen
- title: 'Uitdaging: een score toevoegen'
  challenge: true
- title: Meerdere spellen
- title: 'Uitdaging: startscherm'
  challenge: true
  completion: internal
- title: Afbeeldingen toevoegen
- title: 'Uitdaging: geluid en muziek'
  challenge: true
- title: 'Uitdaging: race naar 10 punten'
  challenge: true
- title: 'Uitdaging: instructiescherm'
  challenge: true
- title: Wat nu?
