---
hero_image: Изображения / мозг game.png
theme: красный
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, production-0, community-0
title: Мозговая игра
description: Узнайте, как создать викторину.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: игры
technologies: царапина
site_areas: проектов
hardware: ''
software: царапина
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Введение
  - 
    title: Создание вопросов
  - 
    title: 'Задача: изменение костюмов'
  - 
    title: 'Задача: добавление оценки'
  - 
    title: Несколько игр
  - 
    title: 'Задача: начальный экран'
  - 
    title: Добавление графики
  - 
    title: 'Задача: улучшенная анимация'
  - 
    title: 'Задача: Звук и музыка'
  - 
    title: 'Задача: гонка до 10 очков'
  - 
    title: 'Вызов: экран инструкций'
