---
hero_image: bilder / hjerne-game.png
listed: true
copyedit: false
title: Hjernespill
description: Lær hvordan du lager en quiz
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Introduksjon
  - 
    title: Lag spørsmål
  - 
    title: Legg til en tidtaker
  - 
    title: 'Utfordring: legg til en poengsum og reaksjoner'
    challenge: true
  - 
    title: Flere spill
  - 
    title: 'Utfordring: Lag en startskjerm'
    challenge: true
  - 
    title: Legg til grafikk
  - 
    title: 'Utfordring: lyd og musikk'
    challenge: true
  - 
    title: 'Utfordring: løp til 10 poeng'
    challenge: true
  - 
    title: 'Utfordring: instruksjonsskjerm'
    challenge: true
  - 
    title: Hva nå?
