---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Trò chơi trí não
description: Tìm hiểu làm thế nào để tạo ra một bài kiểm tra
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Giới thiệu
  - 
    title: Tạo câu hỏi
  - 
    title: Thêm một bộ đếm thời gian
  - 
    title: 'Thử thách: thêm điểm và phản ứng'
    challenge: true
  - 
    title: Nhiều trò chơi
  - 
    title: 'Thử thách: tạo màn hình bắt đầu'
    challenge: true
  - 
    title: Thêm đồ họa
  - 
    title: 'Thử thách: âm thanh và nhạc'
    challenge: true
  - 
    title: 'Thử thách: cuộc đua tới 10 điểm'
    challenge: true
  - 
    title: 'Thử thách: màn hình hướng dẫn'
    challenge: true
  - 
    title: Bước tiếp theo?
