---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Hjernetræning
description: Lær at lave en quiz
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Tillykke Med Fødselsdagen
  - 
    title: Lav spørgsmål
  - 
    title: Tilføj en timer
  - 
    title: 'Udfordring: Tilføj en score og reaktioner'
    challenge: true
  - 
    title: Mange spil
  - 
    title: 'Udfordring: Opret en startskærm'
    challenge: true
  - 
    title: Tilføj grafik
  - 
    title: 'Udfordring: lyd og musik'
    challenge: true
  - 
    title: 'Udfordring: Race til 10 point'
    challenge: true
  - 
    title: 'Udfordring: instruktionsskærm'
    challenge: true
  - 
    title: Hvad er det næste?
