---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Hjernetræning
description: I dette projekt skal du lære, hvordan du laver et tidsbaseret quizprogram, hvor du har 30 sekunder til at svare rigtigt på så mange spørgsmål som muligt.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Hjernetræning
  - 
    title: Create questions
  - 
    title: Add a timer
  - 
    title: 'Challenge: add a score and reactions'
    challenge: true
  - 
    title: Mange spil
  - 
    title: 'Challenge: create a start screen'
    challenge: true
  - 
    title: Add graphics
  - 
    title: 'Challenge: sound and music'
    challenge: true
  - 
    title: 'Challenge: race to 10 points'
    challenge: true
  - 
    title: 'Challenge: instruction screen'
    challenge: true
  - 
    title: What next?
