---
hero_image: images/brain-game.png
theme: rød
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Hjernespillet
description: Lær at lave en quiz.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: spil
technologies: scratch
site_areas: projekter
hardware: ''
software: scratch
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Introduktion
  - 
    title: Hvordan man laver spørgsmål
  - 
    title: 'Udfordring: Ændring af kostumer'
  - 
    title: 'Udfordring: Tilføjelse af en score'
  - 
    title: Mange spil
  - 
    title: 'Udfordring: Startskærmen'
  - 
    title: Tilføjelse af grafik
  - 
    title: 'Udfordring: Forbedret animation'
  - 
    title: 'Udfordring: Lyd og musik'
  - 
    title: 'Udfordring: Kapløb til 10 point'
  - 
    title: 'Udfordring: Instruktionsskærm'
