---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Jogo do cérebro
description: Aprende como criar um quiz.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Criar as perguntas
  - 
    title: 'Desafio: Trocar trajes'
  - 
    title: 'Desafio: Adicionar uma pontuação'
  - 
    title: Múltiplas jogadas
  - 
    title: 'Desafio: Ecrã inicial'
  - 
    title: Inserir ícones
  - 
    title: 'Desafio: Melhorar a animação'
  - 
    title: 'Desafio: Som e música'
  - 
    title: 'Desafio: Correr por 10 pontos'
  - 
    title: 'Desafio: Ecrã de instruções'
