---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jogo de calculo mental
description: Aprende como criar um quiz
version: 3
last_tested: 2018-10-03
steps:
  - 
    title: Jogo de calculo mental
  - 
    title: Crie perguntas
  - 
    title: Adicionar temporizador
  - 
    title: 'Desafio: adicionar uma pontuação e reações'
    challenge: true
  - 
    title: Jogadas múltiplas
  - 
    title: 'Challenge: create a start screen'
    challenge: true
  - 
    title: Add graphics
  - 
    title: 'Challenge: sound and music'
    challenge: true
  - 
    title: 'Challenge: race to 10 points'
    challenge: true
  - 
    title: 'Challenge: instruction screen'
    challenge: true
  - 
    title: What next?
