---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jogo de calculo mental
description: Neste projeto vais aprender a criar um jogo de perguntas sobre a tabuada de multiplicar, no qual terás que conseguir responder um numero máximo de perguntas corretas como possas em 30 segundos.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Jogo de calculo mental
  - 
    title: Create questions
  - 
    title: Add a timer
  - 
    title: 'Challenge: add a score and reactions'
    challenge: true
  - 
    title: Múltiplas jogadas
  - 
    title: 'Challenge: create a start screen'
    challenge: true
  - 
    title: Add graphics
  - 
    title: 'Challenge: sound and music'
    challenge: true
  - 
    title: 'Challenge: race to 10 points'
    challenge: true
  - 
    title: 'Challenge: instruction screen'
    challenge: true
  - 
    title: What next?
