---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jogo de cálculo mental
description: Aprende a criar um teste
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Introdução
  - 
    title: Criar perguntas
  - 
    title: Adicionar um temporizador
  - 
    title: 'Desafio: adicionar uma pontuação e reações'
    challenge: true
  - 
    title: Jogadas múltiplas
  - 
    title: 'Desafio: criar um ecrā inicial'
    challenge: true
  - 
    title: Adicionar gráficos
  - 
    title: 'Desafio: som e música'
    challenge: true
  - 
    title: 'Desafio: corrida até 10 pontos'
    challenge: true
  - 
    title: 'Desafio: ecrã de instruções'
    challenge: true
  - 
    title: O que se segue?
