---
hero_image: images/brain-game.png
theme: vermelho
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programação-0, computação-física-0, fabrico-0, comunidade-0
title: Jogo do cérebro
description: Aprenda como criar um teste.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: jogos
technologies: scratch
site_areas: projetos
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Criação de perguntas
  - 
    title: 'Desafio: Mudar costumes'
  - 
    title: 'Desafio: Adicionar uma pontuação'
  - 
    title: Múltiplos jogos
  - 
    title: 'Desafio: tela inicial'
  - 
    title: Adicionar gráficos
  - 
    title: 'Desafio: Melhorar a animação'
  - 
    title: 'Desafio: Som e música'
  - 
    title: 'Desafio: Corrida para 10 pontos'
  - 
    title: 'Desafio: Tela de instruções'
