---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jogo de calculo mental
description: Aprende como criar um quiz
version: 3
last_tested: 2018-10-03
steps:
  - 
    title: Jogo de calculo mental
  - 
    title: Crie perguntas
  - 
    title: Adicionar temporizador
  - 
    title: 'Desafio: adicionar uma pontuação e reações'
    challenge: true
  - 
    title: Jogadas múltiplas
  - 
    title: 'Desafio: criar uma tela inicial'
    challenge: true
  - 
    title: Adicionar gráficos
  - 
    title: 'Desafio: som e música'
    challenge: true
  - 
    title: 'Desafio: Corrida até 10 pontos'
    challenge: true
  - 
    title: 'Desafio: Ecrã de instruções'
    challenge: true
  - 
    title: O que se segue?
