---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Brain Game
description: Saznajte kako izraditi kviz.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: games
technologies: scratch
site_areas: projekti
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Izrada pitanja
  - 
    title: 'Izazov: Promjena kostima'
  - 
    title: 'Izazov: Dodavanje rezultata'
  - 
    title: Više igara
  - 
    title: 'Izazov: Početni zaslon'
  - 
    title: Dodavanje grafike
  - 
    title: 'Izazov: Poboljšana animacija'
  - 
    title: 'Izazov: Zvuk i glazba'
  - 
    title: 'Izazov: utrka do 10 bodova'
  - 
    title: 'Izazov: zaslon sa uputama'
