---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Mozgalica
description: U ovome projektu ćeš naučiti kako napraviti kviz u kojemu igrač treba odgovoriti na što više pitanja u 30 sekundi.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Create questions
  - 
    title: Add a timer
  - 
    title: 'Challenge: add a score and reactions'
    challenge: true
  - 
    title: Više igara
  - 
    title: 'Challenge: create a start screen'
    challenge: true
  - 
    title: Add graphics
  - 
    title: 'Challenge: sound and music'
    challenge: true
  - 
    title: 'Challenge: race to 10 points'
    challenge: true
  - 
    title: 'Challenge: instruction screen'
    challenge: true
  - 
    title: What next?
