---
hero_image: Kuvien / aivot game.png
listed: true
copyedit: false
title: Aivopeli
description: Opi luomaan tietokilpailu
version: 4.0.2
last_tested: 10.03.2018
steps:
  - 
    title: esittely
  - 
    title: Luo kysymyksiä
  - 
    title: Lisää ajastin
  - 
    title: 'Haaste: lisää pisteet ja reaktiot'
    challenge: true
  - 
    title: Useita pelejä
  - 
    title: 'Haaste: luo aloitusnäyttö'
    challenge: true
  - 
    title: Lisää grafiikkaa
  - 
    title: 'Haaste: ääni ja musiikki'
    challenge: true
  - 
    title: 'Haaste: kilpailu 10 pisteen'
    challenge: true
  - 
    title: 'Haaste: ohje-näyttö'
    challenge: true
  - 
    title: Mitä seuraavaksi?
