---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Juego de Cálculo Mental
description: Aprende a crear un concurso de preguntas y respuestas.
original_url: https://projects.raspberrypi.org/en/projects/brain-game
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introducción
- title: Crear las preguntas
- title: 'Desafío: Cambiar los disfraces'
- title: 'Desafío: Añadir puntuación'
- title: Múltiples partidas
- title: 'Desafío: Pantalla de inicio'
- title: Añadir gráficos
- title: 'Desafío: Mejorar la animación'
- title: 'Desafío: Sonido y música'
- title: 'Desafío: Corre por 10 puntos'
- title: 'Desafío: Pantalla de instrucciones'