---
hero_image: imagenes/juego-mental.png
listed: true
copyedit: false
title: Juego mental
description: Aprende cómo crear una prueba
version: 3
last_tested: 2018-10-03
steps:
  - 
    title: Introducción
  - 
    title: Crear preguntas
  - 
    title: 'Desafío: Cambiar disfraces'
  - 
    title: 'Desafío: Añadir una puntuación y reacciones'
    challenge: true
  - 
    title: Múltiples juegos
  - 
    title: 'Desafío: Pantalla de inicio'
    challenge: true
  - 
    title: Añadir gráficos
  - 
    title: 'Desafío: Sonido y música'
    challenge: true
  - 
    title: 'Desafío: Carrera hasta 10 puntos'
    challenge: true
  - 
    title: 'Desafío: Pantalla de instrucciones'
    challenge: true
  - 
    title: 'Desafío: más colores'
