---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Juego mental
description: Aprende a crear un examen
version: 4.0.2
last_tested: 2018-10-03
steps:
- title: Introducción
- title: Crear preguntas
- title: Añadir un cronómetro
  completion:
  - engaged
- title: 'Desafío: Añadir una puntuación y reacciones'
  challenge: true
- title: Varias partidas
- title: 'Desafío: Crear una pantalla de inicio'
  challenge: true
- title: Añadir gráficos
  completion:
  - internal
- title: 'Desafío: Sonido y música'
  challenge: true
- title: 'Desafío: Carrera hasta 10 puntos'
  challenge: true
- title: 'Desafío: Pantalla de instrucciones'
  challenge: true