---
hero_image: imagenes/juego-mental.png
listed: true
copyedit: false
title: Brain game
description: Learn how to create a quiz
version: 4.0.1
last_tested: 2018-10-03
steps:
  - 
    title: Introducción
  - 
    title: Create questions
  - 
    title: Add a timer
  - 
    title: 'Challenge: add a score and reactions'
  - 
    title: Múltiples juegos
  - 
    title: 'Challenge: create a start screen'
  - 
    title: Add graphics
  - 
    title: 'Challenge: sound and music'
  - 
    title: 'Challenge: race to 10 points'
  - 
    title: 'Challenge: instruction screen'
  - 
    title: What next?
