---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Gêm i'r Ymennydd
description: Dysga sut i greu cwis.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Creu cwestiynau
  - 
    title: 'Her: Newid gwisgoedd'
  - 
    title: 'Her: Ychwanegu sgôr'
    challenge: true
  - 
    title: Gemau lluosog
  - 
    title: 'Her: Dechrau''r gêm2'
    challenge: true
  - 
    title: Ychwanegu graffeg
  - 
    title: 'Her: Perffeithio dy animeiddiad'
    challenge: true
  - 
    title: 'Her: Cerdd a Sain'
    challenge: true
  - 
    title: 'Her: Ras i 10 o bwyntiau'
    challenge: true
  - 
    title: 'Her: Sgrin cyfarwyddiadau'
