---
hero_image: images/brain-game.png
theme: rojo
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creador, diseño-0, programación-0, informática-física-0, fabricación-0, comunidad-0
title: Juego mental
description: Aprenda cómo crear una prueba.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
  - 
    title: Introducción
  - 
    title: Crear preguntas
  - 
    title: 'Desafío: Cambiar disfraces'
  - 
    title: 'Desafío: Agregar una puntuación'
  - 
    title: Juegos múltiples
  - 
    title: 'Desafío: Pantalla de inicio'
  - 
    title: Adding graphics
  - 
    title: 'Challenge: Improved animation'
  - 
    title: 'Challenge: Sound and music'
  - 
    title: 'Challenge: Race to 10 points'
  - 
    title: 'Challenge: Instruction screen'

