---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Gehirntraining
description: Lerne, wie man ein Quiz programmiert.
original_url: https://projects.raspberrypi.org/en/projects/brain-game
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Fragen zusammenstellen
  - 
    title: 'Herausforderung: Kost체m 채ndern'
  - 
    title: 'Aufgabe: Eine Punktzahl hinzuf체gen'
  - 
    title: Mehrmals spielen
  - 
    title: 'Herausforderung: Startbildschirm'
  - 
    title: Grafik hinzuf체gen
  - 
    title: 'Herausforderung: Verbesserte Animation'
  - 
    title: 'Herausforderung: Sound und Musik'
  - 
    title: 'Herausforderung: 10-Punkte-Partie'
  - 
    title: 'Aufgabe: Anweisungsbildschirm'
