---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Gehirntraining
description: Lerne, wie man ein Quiz programmiert
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Einleitung
  - 
    title: Fragen erstellen
  - 
    title: Einen Countdown hinzuf체gen
  - 
    title: 'Herausforderung: F체ge eine Punktzahl und Reaktionen hinzu'
    challenge: true
  - 
    title: Mehrfach spielen
  - 
    title: 'Herausforderung: Erstelle einen Startbildschirm'
    challenge: true
  - 
    title: Grafiken hinzuf체gen
  - 
    title: 'Herausforderung: Kl채nge und Musik'
    challenge: true
  - 
    title: 'Herausforderung: 10-Punkte-Partie'
    challenge: true
  - 
    title: 'Herausforderung: Anleitungsbildschirm'
    challenge: true
  - 
    title: Wie geht es weiter?
