---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Gehirntraining
description: Lerne, wie man ein Quiz programmiert
version: 3
last_tested: 2018-10-03
steps:
  - 
    title: Einleitung
  - 
    title: Fragen zusammenstellen
  - 
    title: Timer hinzufügen
  - 
    title: 'Aufgabe: Eine Punktzahl hinzufügen'
    challenge: true
  - 
    title: Mehrmals spielen
  - 
    title: 'Aufgabe: Start-Bildschirm'
    challenge: true
  - 
    title: Grafik hinzufügen
  - 
    title: 'Aufgabe: Verbesserte Animation'
    challenge: true
  - 
    title: 'Aufgabe: Sound und Musik'
    challenge: true
  - 
    title: 'Aufgabe: Wettrennen zu 10 Punkten'
    challenge: true
  - 
    title: 'Zusatzaufgabe: mehr Stifte'
