---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Gehirntraining
description: Lerne, wie man ein Quiz programmiert
version: 3
last_tested: 2018-10-03
steps:
  - 
    title: Einleitung
  - 
    title: Fragen zusammenstellen
  - 
    title: Einen Timer hinzufügen
  - 
    title: 'Aufgabe: Eine Punktzahl hinzufügen'
    challenge: true
  - 
    title: Mehrmals spielen
  - 
    title: 'Aufgabe: Start-Bildschirm'
    challenge: true
  - 
    title: Grafiken hinzufügen
  - 
    title: 'Herausforderung: Klänge und Musik'
    challenge: true
  - 
    title: 'Herausforderung: 10-Punkte-Partie'
    challenge: true
  - 
    title: 'Herausforderung: Anleitungsbildschirm'
    challenge: true
  - 
    title: Was kommt als nächstes?
