---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Jocul Minții
description: Învățați cum să creați un chestionar.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: jocuri
technologies: scratch
site_areas: proiecte
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Crearea întrebărilor
  - 
    title: 'Provocare: Schimbarea costumelor'
  - 
    title: 'Provocare: adăugarea unui scor'
  - 
    title: Mai multe jocuri
  - 
    title: 'Provocare: Ecranul de start'
  - 
    title: Adăugarea de conținut vizual
  - 
    title: 'Provocare: animație îmbunătățită'
  - 
    title: 'Provocare: Sunete și muzică'
  - 
    title: 'Provocare: Cursă până la 10 puncte'
  - 
    title: 'Provocare: Ecran cu instrucțiuni'
