---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jocul minții
description: Învățați cum să creați un chestionar
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Introducere
  - 
    title: Creați întrebări
  - 
    title: Adăugați un cronometru
  - 
    title: 'Provocare: adăugați un scor și reacții'
    challenge: true
  - 
    title: Jocuri multiple
  - 
    title: 'Provocare: creați un ecran de pornire'
    challenge: true
  - 
    title: Adăugați grafică
  - 
    title: 'Provocare: Sunete și muzică'
    challenge: true
  - 
    title: 'Provocare: Cursa la 10 puncte'
    challenge: true
  - 
    title: 'Provocare: ecran de instrucțiuni'
    challenge: true
  - 
    title: Ce urmează?
