---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Brain Game
description: Învățați cum să creați un chestionar
version: 3
last_tested: 2018-10-03
steps:
  - 
    title: Brain Game
  - 
    title: Creați întrebări
  - 
    title: Adăugați un cronometru
  - 
    title: 'Provocare: adăugați un scor și reacții'
    challenge: true
  - 
    title: Mai multe jocuri
  - 
    title: 'Provocare: creați un ecran de pornire'
    challenge: true
  - 
    title: Adăugați grafică
  - 
    title: 'Provocare: sunet și muzică'
    challenge: true
  - 
    title: 'Provocare: Cursa la 10 puncte'
    challenge: true
  - 
    title: 'Provocare: ecran de instrucțiuni'
    challenge: true
  - 
    title: Ce urmează?
