---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Brain Game
description: În acest proiect vei învăţa cum să creezi, un chestionar cu intrebari din tabla înmulţirii, la care trebuie să răspunzi corect la cât mai multe întrebări în 30 de secunde.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Brain Game
  - 
    title: Create questions
  - 
    title: Add a timer
  - 
    title: 'Challenge: add a score and reactions'
    challenge: true
  - 
    title: Mai multe jocuri
  - 
    title: 'Challenge: create a start screen'
    challenge: true
  - 
    title: Add graphics
  - 
    title: 'Challenge: sound and music'
    challenge: true
  - 
    title: 'Challenge: race to 10 points'
    challenge: true
  - 
    title: 'Challenge: instruction screen'
    challenge: true
  - 
    title: What next?
