---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jogo da Tabuada
description: Aprenda como criar um teste
version: 3
last_tested: 2018-10-03
steps:
  - 
    title: Introdução
  - 
    title: Create questions
  - 
    title: Add a timer
  - 
    title: 'Challenge: add a score and reactions'
    challenge: true
  - 
    title: Vários jogos
  - 
    title: 'Challenge: create a start screen'
    challenge: true
  - 
    title: Add graphics
  - 
    title: 'Challenge: sound and music'
    challenge: true
  - 
    title: 'Challenge: race to 10 points'
    challenge: true
  - 
    title: 'Challenge: instruction screen'
    challenge: true
  - 
    title: O que vem depois?
