---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jogo da Tabuada
description: Aprenda como criar um teste
version: 4.0.2
last_tested: 2018-10-03
steps:
- title: Introdução
- title: Criar perguntas
- title: Adicionar um cronômetro
  completion:
  - engaged
- title: 'Desafio: adicionar uma pontuação e reações'
  challenge: true
- title: Vários jogos
- title: 'Desafio: criar uma tela inicial'
  challenge: true
- title: Adicionar figuras
  completion:
  - internal
- title: 'Desafio: som e música'
  challenge: true
- title: 'Desafio: corrida até 10 pontos'
  challenge: true
- title: 'Desafio: tela de instruções'
  challenge: true
- title: E agora?
