---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jogo da Tabuada
description: Learn how to create a quiz
version: 3
last_tested: 03-10-2018
steps:
  - 
    title: Introduction
  - 
    title: Criar perguntas
  - 
    title: Adicionar um cronômetro
  - 
    title: 'Desafio: adicionar uma pontuação e reações'
    challenge: true
  - 
    title: Multiple games
  - 
    title: 'Desafio: criar uma tela inicial'
    challenge: true
  - 
    title: Adicionar figuras
  - 
    title: 'Desafio: som e música'
    challenge: true
  - 
    title: 'Desafio: corrida até 10 pontos'
    challenge: true
  - 
    title: 'Desafio: Tela de instruções'
    challenge: true
  - 
    title: What next?
