---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Jogo de Raciocínio
description: Aprenda como criar um teste.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: jogos
technologies: scratch
site_areas: projetos
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Criando perguntas
  - 
    title: 'Desafio: Trocar fantasias'
  - 
    title: 'Desafio: Adicionando uma pontuação'
  - 
    title: Vários jogos
  - 
    title: 'Desafio: tela inicial'
  - 
    title: Adicionando gráficos
  - 
    title: 'Desafio: animação melhorada'
  - 
    title: 'Desafio: som e música'
  - 
    title: 'Desafio: Corrida até 10 pontos'
  - 
    title: 'Desafio: tela de instruções'
