---
hero_image: images / brain-game.png
listed: true
copyedit: false
title: Joc cervell
description: Esbrineu com crear un qüestionari
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Introducció
  - 
    title: Crea preguntes
  - 
    title: Afegiu un temporitzador
  - 
    title: 'Desafiament: afegiu una puntuació i reaccions'
    challenge: true
  - 
    title: Diversos jocs
  - 
    title: 'Desafiament: crea una pantalla d''inici'
    challenge: true
  - 
    title: Afegeix gràfics
  - 
    title: 'Desafiament: so i música'
    challenge: true
  - 
    title: 'Desafiament: carrera fins a 10 punts'
    challenge: true
  - 
    title: 'Desafiament: pantalla d''instruccions'
    challenge: true
  - 
    title: Què veig?
