---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Možganska igra
description: Nauči se ustvariti kviz
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Uvod
  - 
    title: Ustvari vprašanja
  - 
    title: Dodaj časovnik
  - 
    title: 'Izziv: dodaj rezultat in reakcije'
    challenge: true
  - 
    title: Več iger
  - 
    title: 'Izziv: ustvari začetni zaslon'
    challenge: true
  - 
    title: Dodaj grafiko
  - 
    title: 'Izziv: zvok in glasba'
    challenge: true
  - 
    title: 'Izziv: dirka do 10 točk'
    challenge: true
  - 
    title: 'Izziv: zaslon z navodili'
    challenge: true
  - 
    title: Kaj sledi?
