---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Brain game
description: Learn how to create a quiz
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Úvod
  - 
    title: Vytvoření otázek
  - 
    title: Přidej časovač
  - 
    title: 'Výzva: přidej skóre a reakce'
    challenge: true
  - 
    title: Více her
  - 
    title: 'Výzva: Úvodní obrazovka'
    challenge: true
  - 
    title: Přidej grafiku
  - 
    title: 'Výzva: zvuky a hudba'
    challenge: true
  - 
    title: 'Výzva: desetibodový závod'
    challenge: true
  - 
    title: 'Výzva: nápověda ke hře'
    challenge: true
  - 
    title: Co dál?
