---
hero_image: images / agy-game.png
listed: true
copyedit: false
title: Agy játék
description: Ismerje meg, hogyan kell létrehozni egy kvízet
version: 4.0.2
last_tested: 2018/10/03
steps:
  - 
    title: Bevezetés
  - 
    title: Kérdések létrehozása
  - 
    title: Idõzítõ hozzáadása
  - 
    title: 'Kihívás: hozzáad egy pontszámot és reakciókat'
    challenge: true
  - 
    title: Több játék
  - 
    title: 'Kihívás: hozzon létre egy kezdőképernyőt'
    challenge: true
  - 
    title: Grafika hozzáadása
  - 
    title: 'Kihívás: hang és zene'
    challenge: true
  - 
    title: 'Kihívás: verseny 10 pontra'
    challenge: true
  - 
    title: 'Kihívás: utasítás képernyő'
    challenge: true
  - 
    title: Mi a következő?
