---
hero_image: 圖片/腦game.png
listed: true
copyedit: false
title: 腦力遊戲
description: 了解如何創建測驗
version: 4.0.2
last_tested: 2018年10月3日
steps:
  - 
    title: 介紹
  - 
    title: 創建問題
  - 
    title: 添加計時器
  - 
    title: '挑戰：添加分數和反應'
    challenge: true
  - 
    title: 多場比賽
  - 
    title: '挑戰：創建一個開始屏幕'
    challenge: true
  - 
    title: 添加圖形
  - 
    title: '挑戰：聲音和音樂'
    challenge: true
  - 
    title: '挑戰：比賽達到10分'
    challenge: true
  - 
    title: '挑戰：指導屏幕'
    challenge: true
  - 
    title: 接下來是什麼？
