---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Juego Mental
description: Aprender a cómo crear una prueba
version: 4.0.2
last_tested: 03-10-2018
steps:
  - 
    title: Introducción
  - 
    title: Crear preguntas
  - 
    title: Agregar un temporizador
    completion:
      - engaged
  - 
    title: 'Desafío: agregar una puntuación y reacciones'
    challenge: true
  - 
    title: Varias partidas
  - 
    title: 'Desafío: crear una pantalla de inicio'
    challenge: true
  - 
    title: Agregar gráficos
    completion:
      - internal
  - 
    title: 'Desafío: sonido y música'
    challenge: true
  - 
    title: 'Desafío: correr hasta 10 puntos'
    challenge: true
  - 
    title: 'Desafío: pantalla de instrucciones'
    challenge: true
  - 
    title: '¿Qué sigue?'
