---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: لعبة العقل
description: تعلم كيف تُنشئ اختبارًا قصيرًا
version: 4.0.2
last_tested: 2018-10-03
steps:
- title: المقدمة
- title: إنشاء الأسئلة
- title: إضافة مؤقت
  completion:
  - engaged
- title: 'التحدي: إضافة سجل نقاط وردود فعل'
  challenge: true
- title: ألعاب متعددة
- title: 'التحدي: إنشاء شاشة البداية'
  challenge: true
- title: إضافة رسومات
  completion:
  - internal
- title: 'التحدي: الصوت والموسيقى'
  challenge: true
- title: 'التحدي: سباق حتى 10 نقاط'
  challenge: true
- title: 'التحدي: شاشة التعليمات'
  challenge: true
- title: ما هي الخطوة التالية؟
