---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: لعبة العقل
description: تعلم كيف تُنشئ اختبارًا قصيرًا
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: المقدمة
  - 
    title: إنشاء أسئلة
  - 
    title: 'التحدي: تغيير المظاهر'
  - 
    title: 'التحدي: إضافة درجة'
    challenge: true
  - 
    title: ألعاب متعددة
  - 
    title: 'التحدي: شاشة البدء'
    challenge: true
  - 
    title: إضافة رسومات
  - 
    title: 'التحدي: رسوم متحركة محسنة'
    challenge: true
  - 
    title: 'التحدي: الصوت والموسيقى'
    challenge: true
  - 
    title: 'التحدي: سباق حتى 10 نقاط'
    challenge: true
  - 
    title: ما التالي؟
