---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Tabliczka mnożenia
description: Naucz się, jak wykonać quiz z tabliczki mnożenia.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Tabliczka mnożenia
  - 
    title: Create questions
  - 
    title: Add a timer
  - 
    title: 'Challenge: add a score and reactions'
    challenge: true
  - 
    title: Wielokrotne gry
  - 
    title: 'Challenge: create a start screen'
    challenge: true
  - 
    title: Add graphics
  - 
    title: 'Challenge: sound and music'
    challenge: true
  - 
    title: 'Challenge: race to 10 points'
    challenge: true
  - 
    title: 'Challenge: instruction screen'
    challenge: true
  - 
    title: What next?
