---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Gra dla mózgu
description: Dowiedz się, jak utworzyć quiz.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Tworzenie pytań
  - 
    title: 'Wyzwanie: zmiana kostiumów'
  - 
    title: 'Wyzwanie: Dodawanie wyniku'
  - 
    title: Wielokrotne gry
  - 
    title: 'Wyzwanie: ekran startowy'
  - 
    title: Dodawanie grafiki
  - 
    title: 'Wyzwanie: ulepszona animacja'
  - 
    title: 'Wyzwanie: dźwięk i muzyka'
  - 
    title: 'Wyzwanie: Wyścig do 10 punktów'
  - 
    title: 'Wyzwanie: okno instrukcji'
