---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Tabliczka mnożenia
description: Dowiedz się, jak utworzyć quiz
version: 4.0.2
last_tested: 2018-10-03
steps:
  - 
    title: Wprowadzenie
  - 
    title: Twórz pytania
  - 
    title: Dodawanie stopera
  - 
    title: 'Wyzwanie: dodaj wynik i reakcje'
    challenge: true
  - 
    title: Wielokrotne gry
  - 
    title: 'Wyzwanie: utwórz ekran startowy'
    challenge: true
  - 
    title: Dodaj grafikę
  - 
    title: 'Wyzwanie: dźwięk i muzyka'
    challenge: true
  - 
    title: 'Wyzwanie: wyścig do 10 punktów'
    challenge: true
  - 
    title: 'Wyzwanie: ekran instrukcji'
    challenge: true
  - 
    title: Co dalej?
