---
hero_image: images / brain-game.png
listed: true
copyedit: false
title: Mozgová hra
description: Naučte sa, ako vytvoriť kvíz
version: 4.0.2
last_tested: 10.03.2018
steps:
  - 
    title: úvod
  - 
    title: Vytvorte otázky
  - 
    title: Pridať časovač
  - 
    title: 'Výzva: pridajte skóre a reakcie'
    challenge: true
  - 
    title: Viacnásobné hry
  - 
    title: 'Výzva: vytvorte úvodnú obrazovku'
    challenge: true
  - 
    title: Pridajte grafiku
  - 
    title: 'Výzva: zvuk a hudba'
    challenge: true
  - 
    title: 'Výzva: závod na 10 bodov'
    challenge: true
  - 
    title: 'Výzva: obrazovka s pokynmi'
    challenge: true
  - 
    title: Čo ďalej?
