---
hero_image: images / hjärn game.png
listed: true
copyedit: false
title: Hjärnspel
description: Lär dig hur du skapar en frågesport
version: 4.0.2
last_tested: 2018/10/03
steps:
  - 
    title: Introduktion
  - 
    title: Skapa frågor
  - 
    title: Lägg till en timer
  - 
    title: 'Utmaning: lägg till en poäng och reaktioner'
    challenge: true
  - 
    title: Flera spel
  - 
    title: 'Utmaning: Skapa en startskärm'
    challenge: true
  - 
    title: Lägg till grafik
  - 
    title: 'Utmaning: ljud och musik'
    challenge: true
  - 
    title: 'Utmaning: ras till 10 poäng'
    challenge: true
  - 
    title: 'Utmaning: instruktionsskärm'
    challenge: true
  - 
    title: Vad nästa?
