---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Mozgalica
description: Nauči kako da napraviš kviz.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Izrada pitanja
  - 
    title: 'Izazov: Promjena kostima'
  - 
    title: 'Izazov: Dodavanje bodova'
    challenge: true
  - 
    title: Više igara
  - 
    title: 'Izazov: Početni ekran'
    challenge: true
  - 
    title: Dodavanje grafika
  - 
    title: 'Izazov: Poboljšana animacija'
    challenge: true
  - 
    title: 'Izazov: Zvuk i muzika'
    challenge: true
  - 
    title: 'Izazov: Trka do 10 bodova'
    challenge: true
  - 
    title: 'Izazov: Ekran sa uputstvima'
