---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Jeu d'ingéniosité
description: Apprends comment créer un quiz
version: 3
last_tested: 2018-10-03
steps:
  - 
    title: Introduction
  - 
    title: Création des questions
  - 
    title: 'Défi: Changement de costumes'
  - 
    title: 'Défi: Ajout d''un pointage'
    challenge: true
  - 
    title: Jeux multiples
  - 
    title: 'Défi: Écran du début'
    challenge: true
  - 
    title: Ajout de graphisme
  - 
    title: 'Défi: Animation améliorée'
    challenge: true
  - 
    title: 'Défi: Son et musique'
    challenge: true
  - 
    title: 'Défi: Course à 10 points'
    challenge: true
  - 
    title: 'Défi : plus de crayons'
