---
hero_image: images/brain-game.png
theme: rouge
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Jeu d'ingéniosité
description: Apprends comment créer un quiz.
original_url: https://projects.raspberrypi.org/en/projects/brain-game
interests: jeux
technologies: scratch
site_areas: projets
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Création des questions
  - 
    title: 'Défi: Changement de costumes'
  - 
    title: 'Défi: Ajout d''un pointage'
  - 
    title: Jeux multiples
  - 
    title: 'Défi: Écran du début'
  - 
    title: Ajout de graphisme
  - 
    title: 'Défi: Animation améliorée'
  - 
    title: 'Défi: Son et musique'
  - 
    title: 'Défi: Course à 10 points'
  - 
    title: 'Défi: Écran d''instruction'
