---
hero_image: images/brain-game.png
listed: true
copyedit: false
title: Giochi di Mente
description: Impara a creare un quiz.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Creare domande
  - 
    title: 'Sfida: Cambia costumi'
  - 
    title: 'Sfida: Aggiungi un punteggio'
    challenge: true
  - 
    title: Giochi multipli
  - 
    title: 'Sfida: Inizia schermata'
    challenge: true
  - 
    title: Aggiungi grafiche
  - 
    title: 'Sfida: Animazione migliorata'
    challenge: true
  - 
    title: 'Sfida: Suono e musica'
    challenge: true
  - 
    title: 'Sfida: Gareggia fino ai 10 punti'
    challenge: true
  - 
    title: 'Sfida: Schermata istruzioni'
